# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
#  vmImage: ubuntu-latest
  name: LinuxAgents
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ArmDevOpsConnect'
    subscriptionId: 'daec4827-7402-4d03-a7c9-b48171487bee'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'TestRG'
    location: 'Japan East'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/VirexLai/DevOpsLabs/refs/heads/main/vm_arm/vm_2.json'
#    overrideParameters: '-projectName devopsarm'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
