# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
#  vmImage: ubuntu-latest
  name: LinuxAgents
  variables:
    -name : RGName
    value: 'TestRG9487'
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ArmDevOpsConnect'
    subscriptionId: 'daec4827-7402-4d03-a7c9-b48171487bee'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'TestRG9487'
    location: 'Japan East'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/VirexLai/DevOpsLabs/refs/heads/main/vm_arm/vm_2.json'
#    overrideParameters: '-projectName devopsarm'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- task2: Powershell@4
    displayName: 'Run a one-line script'
    inputs:
      targetType: 'inline'
      script:
        write-host $(RGName)
    pwsh: ./test2.ps1
    displayName: 'Done for assign'
